package no.nav.arena_tiltak_aktivitet_acl.historiserteDeltakerFix

import java.time.LocalDate
import java.time.LocalDateTime

/*
JN_OPERATION,
JN_ORACLE_USER,
JN_DATETIME,
JN_APPLN,
JN_SESSION,
JN_TIMESTAMP,
TILTAKDELTAKER_ID,
PERSON_ID,
TILTAKGJENNOMFORING_ID,
DELTAKERSTATUSKODE,
DELTAKERTYPEKODE,
BEGRUNNELSE_PRIORITERING,
REG_DATO,
REG_USER,
MOD_DATO,
MOD_USER,
DATO_FRA,
DATO_TIL,
PROSENT_DELTID,
BRUKERID_STATUSENDRING,
DATO_STATUSENDRING,
AKTIVITET_ID,
BRUKERID_ENDRING_PRIORITERING,
DATO_ENDRING_PRIORITERING

 */
enum class JnOperation {INS, UPD, DEL}
enum class DeltakerStatusKode { AKTUELL, INFOMOETE, JATAKK, TILBUD, VENTELISTE, FULLF, GJENN, GJENN_AVB, GJENN_AVL, IKKAKTUELL, AVSLAG, DELAVB, IKKEM, NEITAKK}
data class ArenaDeltakelseLogg(
	val JN_OPERATION: JnOperation,
	val JN_ORACLE_USER: String,
	val JN_DATETIME: LocalDate? = null, //10.01.23 16:19
	val JN_APPLN: String? = null,
	val JN_SESSION: String? = null,
	val JN_TIMESTAMP: LocalDateTime? = null,   // 10.01.2023 16.19.12,792457000
	val TILTAKDELTAKER_ID: Long,
	val PERSON_ID: Long,
	val TILTAKGJENNOMFORING_ID: Long,
	val DELTAKERSTATUSKODE: DeltakerStatusKode,
	val DELTAKERTYPEKODE: String? = null,
	val BEGRUNNELSE_PRIORITERING: String? = null,
	val REG_DATO: LocalDateTime,
	val REG_USER: String,
	val MOD_DATO: LocalDateTime,
	val MOD_USER: String,
	val DATO_FRA: LocalDate? = null,
	val DATO_TIL: LocalDate? = null,
	val PROSENT_DELTID: Int? = null,
	val BRUKERID_STATUSENDRING: String,
	val DATO_STATUSENDRING: String? = null,
	val AKTIVITET_ID: Long,
	val BRUKERID_ENDRING_PRIORITERING: String? = null,
	val DATO_ENDRING_PRIORITERING: String? = null,
)
