package no.nav.arena_tiltak_aktivitet_acl.historiserteDeltakerFix

data class JournalfoertArenaDeltakelse(
	val TILTAKDELTAKER_ID: Long,
	val PERSON_ID: Long? = null,
	val TILTAKGJENNOMFORING_ID: Long,
	val DELTAKERSTATUSKODE: String,
	val DELTAKERTYPEKODE: String? = null,
	val AARSAKVERDIKODE_STATUS: String? = null,
	val OPPMOTETYPEKODE: String? = null,
	val PRIORITET: Int? = null,
	val BEGRUNNELSE_INNSOKT: String? = null,
	val BEGRUNNELSE_PRIORITERING: String? = null,
	val REG_DATO: String? = null,
	val REG_USER: String? = null,
	val MOD_DATO: String,
	val MOD_USER: String? = null,
	val DATO_SVARFRIST: String? = null,
	val DATO_FRA: String? = null,
	val DATO_TIL: String? = null,
	val BEGRUNNELSE_STATUS: String? = null,
	val PROSENT_DELTID: Float? = null,
	val BRUKERID_STATUSENDRING: String,
	val DATO_STATUSENDRING: String? = null,
	val AKTIVITET_ID: Long,
	val BRUKERID_ENDRING_PRIORITERING: String? = null,
	val DATO_ENDRING_PRIORITERING: String? = null,
	val DOKUMENTKODE_SISTE_BREV: String? = null,
	val STATUS_INNSOK_PAKKE: String? = null,
	val STATUS_OPPTAK_PAKKE: String? = null,
	val OPPLYSNINGER_INNSOK: String? = null,
	val PARTISJON: Int? = null,
	val BEGRUNNELSE_BESTILLING: String? = null,
	val ANTALL_DAGER_PR_UKE: Int? = null
)
